### ISSUE TITLE
Error during robust_DivideMix training

### ISSUE THREAD

**Issue by nikokks** [zjfheart/BadLabels#1]
Hi,

First of all, congratulations for your work !

When I run 
```
python robust_dividemix.py --gpu 0 --r 02  --dataset 'cifar100' --log 'robdm_bad' --noise-file '../eval_badlabels/noise/badlabels_cifar100_r0.2.json' --warmup 20 --lam 1 --tol 0.01 --max-iter 500 --noise-mode 'bad' &
```

it outputs this
```
load noise labels from ../eval_badlabels/noise/badlabels_cifar100_r0.1.json ..
===> epoch: 20, lambda: 1.0.
gmm.means:  [[0.52740902]
 [0.42178395]]
gmm.means:  [[0.40338232]
 [0.5466281 ]]
gmm0.means:  [[0.42655838]
 [0.43710862]]
gmm0.converged:  True
gmm0.n_iter_ 127
gmm0.means:  [[0.46136058]
 [0.44749019]]
gmm0.converged:  True
gmm0.n_iter_ 162
Train Net1
load noise labels from ../eval_badlabels/noise/badlabels_cifar100_r0.1.json ..
labeled data has a size of 1645
num of clean data is 1135 (69.00%)
load noise labels from ../eval_badlabels/noise/badlabels_cifar100_r0.1.json ..
unlabeled data has a size of 48355
num of clean data is 43865 (90.71%)
756
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "robust_dividemix.py", line 77, in train
    inputs_u, inputs_u2 = unlabeled_train_iter.next()
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "robust_dividemix.py", line 374, in <module>
    train(epoch, net1, net2, optimizer1, labeled_trainloader, unlabeled_trainloader)  # train net1
  File "robust_dividemix.py", line 80, in train
    inputs_u, inputs_u2 = unlabeled_train_iter.next()                 
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'
```
it seems that the code does not go to except.

**Comment by SongBo1999** [comment]
Hi,

First of all, thank you for your feedback. 

It appears to be a problem caused by differences in PyTorch versions. This code module worked well for me using **PyTorch 1.13.0**. 

I suggest trying different ways of calling the ```next()``` function to accommodate your PyTorch version, such as ```next(unlabeled_train_iter)```. Alternatively, you could try using the same PyTorch version as mine.

Best wishes,
Bo
